import JSZip from "jszip";

export interface BundleData {
  entityName: string;
  schemaType: string;
  jsonSchema: Record<string, any>;
  url: string;
  date: string;
}

export async function generateEnterpriseBundle(data: BundleData): Promise<Blob> {
  const zip = new JSZip();
  const safeName = (data.entityName || "schema").toLowerCase().replace(/[^a-z0-9]/g, "-");
  const folder = zip.folder(`schemacraft-${safeName}-bundle`);

  const jsonString = JSON.stringify(data.jsonSchema, null, 2);

  // 1. Raw JSON-LD File
  folder?.file(`${safeName}-schema.json`, jsonString);

  // 2. Next.js 15 App Router Server Component (TypeScript)
  const nextJsCode = `/**
 * SchemaCraft AI - Next.js 15 App Router Structured Data Component
 * Generated on: ${data.date}
 * Entity: ${data.entityName} (${data.schemaType})
 * 
 * Usage:
 * Import and render in your app/page.tsx or app/layout.tsx:
 * import { SchemaJsonLd } from './SchemaJsonLd';
 * 
 * export default function Page() {
 *   return (
 *     <>
 *       <SchemaJsonLd />
 *       <main>Your Page Content</main>
 *     </>
 *   );
 * }
 */

import React from 'react';

export function SchemaJsonLd() {
  const structuredData = ${jsonString};

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
    />
  );
}

export default SchemaJsonLd;
`;
  folder?.file(`SchemaJsonLd.tsx`, nextJsCode);

  // 3. Shopify Liquid Theme Snippet
  const shopifyLiquid = `{%- comment -%}
  SchemaCraft AI - Shopify JSON-LD Snippet
  Entity: ${data.entityName} (${data.schemaType})
  Generated: ${data.date}

  INSTALLATION INSTRUCTIONS:
  1. Go to Shopify Admin > Online Store > Themes > Edit code.
  2. Under 'Snippets', click 'Add a new snippet', name it 'schemacraft-seo'.
  3. Paste the contents of this file into 'snippets/schemacraft-seo.liquid'.
  4. Open 'layout/theme.liquid' and insert {% render 'schemacraft-seo' %} before the closing </head> tag.
{%- endcomment -%}

<script type="application/ld+json">
${jsonString}
</script>
`;
  folder?.file(`schemacraft-seo.liquid`, shopifyLiquid);

  // 4. WordPress functions.php Hook (PHP)
  const wpPhpCode = `<?php
/**
 * SchemaCraft AI - WordPress Header Schema Injector
 * Entity: ${data.entityName} (${data.schemaType})
 * Generated: ${data.date}
 * 
 * INSTALLATION INSTRUCTIONS:
 * 1. Open your theme's functions.php file (or use a Code Snippets plugin).
 * 2. Paste the code below at the end of functions.php.
 */

function schemacraft_inject_json_ld_schema() {
    ?>
    <script type="application/ld+json">
    ${jsonString}
    </script>
    <?php
}
add_action('wp_head', 'schemacraft_inject_json_ld_schema', 1);
`;
  folder?.file(`wordpress-schema.php`, wpPhpCode);

  // 5. Official Commercial Perpetual License Agreement
  const commercialLicense = `================================================================================
SCHEMACRAFT AI - OFFICIAL PERPETUAL COMMERCIAL LICENSE
================================================================================
Issued to: Verified SchemaCraft Pro License Holder
Product: Enterprise JSON-LD & Generative Engine Schema Assets
License Type: Commercial, Perpetual, Royalty-Free, Worldwide
Issued Date: ${data.date}

GRANT OF RIGHTS:
SchemaCraft AI hereby grants the licensee an irrevocable, perpetual, non-exclusive,
worldwide license to use, integrate, modify, and deploy the generated structured data 
schemas across an unlimited number of personal, commercial, enterprise, and client projects.

PERMITTED USES:
1. Commercial deployment across unlimited production client websites and web applications.
2. Unlimited embedding in SaaS products, e-commerce stores, client deliverables, and agencies.
3. Modification, adaptation, and extension of the JSON-LD schemas, Next.js components, 
   Shopify snippets, and WordPress hooks.
4. No attribution or backlinks required.

RESTRICTIONS:
The licensee may not resell, sub-license, or redistribute the SchemaCraft AI core generator 
software as a standalone competing schema generator service.

100% VALIDATION GUARANTEE:
All schemas generated by SchemaCraft AI are guaranteed to meet Schema.org v26.0 standards 
and Google Rich Results Test validation criteria.

Support & Inquiries: support@schemacraft-ai.site
SchemaCraft AI Labs | https://schemacraft-ai.site
================================================================================
`;
  folder?.file(`COMMERCIAL_LICENSE.txt`, commercialLicense);

  // 6. GEO 2026 Exclusive Citation Optimization Playbook
  const geoPlaybook = `# The 2026 Generative Engine Optimization (GEO) Technical Playbook
**By SchemaCraft AI Architect Labs**

## Introduction
Generative Engine Optimization (GEO) is the discipline of optimizing digital entities so that Large Language Model (LLM) search engines—including Perplexity AI, Google AI Overviews, ChatGPT Search, and Claude—retrieve, ground, and cite your brand with deterministic accuracy.

---

## 1. The 3 Pillars of Generative Citation
1. **Deterministic Schema Graph Grounding**:
   - Provide direct \`@id\` URI anchors for your organization, product, and software applications.
   - Ground pricing, availability, aggregate ratings, and operating system attributes in clean JSON-LD.
2. **Bottom Line Up Front (BLUF) Content Structuring**:
   - Every key entity page must feature a 40–60 word deterministic summary directly answering the search query before any marketing copy.
   - LLM chunking algorithms assign highest vector weight to lead paragraphs.
3. **Machine-Readable Table Specifications**:
   - Use structured HTML tables and Key-Value pairs alongside Schema.org markup.
   - RAG ingestion pipelines parse clean key-value structures 3.2x faster than unstructured text.

---

## 2. Platform Implementation Checklist
- [x] Place JSON-LD in the \`<head>\` of the document for immediate bot execution.
- [x] Verify zero syntax errors using [Google Rich Results Test](https://search.google.com/test/rich-results).
- [x] Check entity taxonomy against [Schema.org Validator](https://validator.schema.org/).
- [x] Ensure \`robots.txt\` allows \`GPTBot\`, \`PerplexityBot\`, and \`Google-Extended\`.

---

© 2026 SchemaCraft AI. All rights reserved.
`;
  folder?.file(`GEO_OPTIMIZATION_PLAYBOOK_2026.md`, geoPlaybook);

  // Generate Zip Blob
  return await zip.generateAsync({ type: "blob" });
}
